### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by sillero** [riccardoscalco/crayon#2]
Hi there o/ nice project you got here :)

I forked and made some modifications, if you care to take a look. https://github.com/sillero/crayon

Basically:
- `color-` prefix to avoid problems with variable names in a project
- template based generation for all stylesheets
- color sorting, to more easily select a color

**Comment by fredericksilva** [comment]
Nice Modifications [View here](https://github.com/riccardoscalco/crayon/compare/master...sillero:master)

:+1:

**Comment by riccardoscalco** [comment]
Thanks man! I definitively have to learn gulp.

About the prefix, I understand the point,  but I have a question: do you think is really necessary? On one side you have the benefit of preventing variable reassignments, but on the other side a prefix can result to be annoying. I decided to avoid a prefix because variables reassignment happens on a vertical order, therefore importing crayon at the very beginning of your stylesheet should not reassign variables. Moreover,  css colors, like "seagreen" or "bisque", do not have a prefix and I found reasonable to do the same choice.

In situation like this I would prefer to take the laziest solution and see if people needs a prefix, I wonder of  what are your thoughts.

**Comment by sillero** [comment]
I get your point about the prefix.
We could leave the prefix property blank and let the user fill it as needed and recompile the stylesheets.
How about that?

**Comment by riccardoscalco** [comment]
Good solution. I would like to merge your fork, can you send a pull request? Thanks.
